spring:
  application:
    name: payment-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:9000}"

payment:
  simulation:
    success-rate: ${PAYMENT_SUCCESS_RATE:70}
    min-delay-ms: ${PAYMENT_MIN_DELAY:500}
    max-delay-ms: ${PAYMENT_MAX_DELAY:2000}
